{% set build_version = "1.32.0" %}
{% set arch = "ppc64le" %}    #[ppc64le]
{% set arch = "64" %}    #[x86_64]


package:
  name: dali
  version: {{ build_version }}

source:
  git_url: https://github.com/NVIDIA/DALI/
  git_rev: v{{ build_version }}
  patches:
    - 0002-cxx11-abi.patch
    - 0303-Fixed-errors-encountered-with-GCC-11.patch
    - 0304-Fixed-Protobuf-detection-via-cmake.patch

build:
  number: 2
  string: h{{ PKG_HASH }}_cuda{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  script_env:
    - CUDA_HOME

outputs:
  - name: dali-tf-plugin
    script: build-dali-tf-plugin.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config {{ pkgconfig }}
        - cmake {{ cmake }}
        - make
        - cudatoolkit {{ cudatoolkit }}
        - protobuf {{ protobuf }}
        - libprotobuf-static {{ libprotobuf }}
        - jpeg-turbo {{ jpegturbo }}
        - dali-ffmpeg
        - python {{ python }}
        - lmdb {{ lmdb }}
        - libsndfile
        - python-clang {{ clang }}
        - libtar {{ libtar }}
        - setuptools {{ setuptools }}
        - ml_dtypes {{ ml_dtypes }}
      host:
        - cudatoolkit {{ cudatoolkit }}
        - dali
        - python {{ python }}
        - setuptools {{ setuptools }}
        - dali-ffmpeg
        - ml_dtypes {{ ml_dtypes }}
      run:
        - python {{ python }}
        - future {{ future }}
        - tensorflow {{ tensorflow }}
        - cudatoolkit {{ cudatoolkit }}
        - opencv {{ opencv }}
        - jpeg-turbo {{ jpegturbo }}
        - lmdb                            # versioning handled by run_exports
        - libsndfile
        - libtiff                         # versioning handled by run_exports
        - libvorbis                       # versioning handled by run_exports
        - dali
        - ml_dtypes {{ ml_dtypes }}
      
about:
  home: https://github.com/NVIDIA/DALI
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
     A library containing both highly optimized building blocks and an execution
     engine for data pre-processing in deep learning applications
  description: |
     A library containing both highly optimized building blocks and an execution
     engine for data pre-processing in deep learning applications
  dev_url: https://github.com/NVIDIA/DALI
  doc_url: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/index.html

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
